GET http://localhost:5500/reqUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgxMzg0ODQ5LCJleHAiOjE2ODEzODQ4Nzl9.LcBr7LYq7LXdTIa1fIw_fr_g9ZfyI0z7Uwn9N24fpSI

###

POST http://localhost:5500/login
Content-Type: application/json

{
   "username":"usernamedemo1",
   "password":"passworddemo1"
}
###
POST http://localhost:5500/changeUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgxNzk1MjcyLCJleHAiOjE2ODE3OTUzMDJ9.WSdMHvbfnjuzpOh0TNzHO5WU4kqF_NFcYyCAnFOrJP0
Content-Type: application/json

{
   "listCart":[{
  "id": "1",
  "url": "https://asset.msi.com/resize/image/global/product/product_162175108621129650150f18f256a57cdb5001e680.png62405b38c58fe0f07fcef2367d8a9ba1/400.png",
  "title": "Msi Bravo",
  "brand": "Msi",
  "type": "laptop",
  "price": 800,
  "quantity": 1,
  "total": 800,
  "detail": []
 }]
}

###
POST http://localhost:5500/refresh
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6Ijk5M2E2ZjA3NjMzYmE1ODc0MGY2ZTljODYxZDViNWZiNDUwMDAzODQ4NGMzMTE0YzQyN2JlNjNiNWE4NzUyNDQwNzBlOWRjOGY3YWFlM2FjYTJjNzlmNzU0NzcwMGFkNjRhZjBkODVmZGE3ZDc0ODk4NGRjZWYzODNjMTM3ZjRiIiwiaWF0IjoxNjgxNzg4MzM3LCJleHAiOjE2ODIyMjAzMzd9.xwCasvYQZI-OOrKpZ-8XGefug6I_pfTkpCpOTaS5e3o"
}