GET http://localhost:5500/reqUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAxNTE4OTMsImV4cCI6MTY4MDE1MTkyM30.PeUim5gujV7PL9wjYCt9gaKeg2ymdHn-nMnL4PnvbCU
###
POST http://localhost:5500/login
Content-Type: application/json

{
    "username" : "usernamedemo1",
    "password": "passworddemo1"
}

###

POST http://localhost:5500/refresh
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IjZkMTE4ZDM1YjQ3NjJiODEzMTYzYWM4NjgzZjJlZjJmZTQxZDc2NzBmOTFjMTYyZjUxODY4NjM1MTJjYjgwMmMxMTM3MTAzMzJmYTE4YjcwZDY0Mzk0ODExMDA3ZTMzZjUzNjIyNTA1OTU1Nzk1NjgyMmM0MGU0YTU0NWU2NzNlIiwiaWF0IjoxNjgwMTUyMTM5LCJleHAiOjE2ODA1ODQxMzl9.NaVW1GPHNOdqW7u4iuqUejGRa8WGqzQsTxWurQWtGE8