GET http://localhost:5500/reqUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAxNTE4OTMsImV4cCI6MTY4MDE1MTkyM30.PeUim5gujV7PL9wjYCt9gaKeg2ymdHn-nMnL4PnvbCU
###
POST http://localhost:5500/login
Content-Type: application/json

{
    "username" : "usernamedemo1",
    "password": "passworddemo1"
}

###

POST http://localhost:5500/refresh
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6Ijk5NzJhODIzZjNjNjk5OTAzMWU5NWEzMDBjY2Q1ZmIwYTY0NTRhNTkwYzMyYTc0NDdkODZkYmU1MjZlZTAwNzBmNWQ0YjgyYTA4YWU5OWMzNTE1NjllYjg4NTg0ZGJkZWY1MzUzOGUwYWVhODBhODBiYjczZGJhOWZjNjE0MzQzIiwiaWF0IjoxNjgwMTUxMjI2LCJleHAiOjE2ODA1ODMyMjZ9.4v7ZtV9e2Unto3xsdBI6ckHAA2xfPfDvvpe0UTWzsXg