GET http://localhost:5500/reqUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwMTQzMTEwLCJleHAiOjE2ODAxNDMxNDB9.z-Ujv4f6W7DJbBxJvafq9K-VharFtHq56Q42jbLlVow
###
POST http://localhost:5500/login
Content-Type: application/json

{
    "username" : "usernamedemo1",
    "password": "passworddemo1"
}
