GET http://localhost:5500/reqUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgxODA5NDAyLCJleHAiOjE2ODE4MTAwMDJ9.AJFujnXuTWZfGYx3iXWhlvWK4loFgdGwY-d22YDXgjo

###

POST http://localhost:5500/login
Content-Type: application/json

{
   "username":"usernamedemo1",
   "password":"passworddemo1"
}
###
POST http://localhost:5500/changeuser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgxODA5NDAyLCJleHAiOjE2ODE4MTAwMDJ9.AJFujnXuTWZfGYx3iXWhlvWK4loFgdGwY-d22YDXgjo
Content-Type: application/json

{
   "fullName":""
}

###
POST http://localhost:5500/refresh
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgxODA0ODUxLCJleHAiOjE2ODE4MDU0NTF9.pFXmz8MUictpynz-dwa_TLVAfFZTQVbfuOuHTrvQ3ck"
}