GET http://localhost:5500/reqUser
Authorization: Beaer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjgwNzU1ODYwLCJleHAiOjE2ODA3NTU4OTB9.FeTtnuqemgH4NceCX4f3CTHl7_1JEYTWTl3xeKOWBBs

###
POST http://localhost:5000/login
Content-Type: application/json

{
   "email":"dfast1705037532@gmail.com"
}

###
POST http://localhost:5000/refresh
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6Ijk3ZDY2Y2ZkNjQxMzM2NmJjY2Q4NjBiYWRmYTE5NjNhMTU5NmRjZTQyZGQ1ZWZiMTRiOGQwMzBlYzUwZDhhNmEzMWM2MDBhOTAxMjNhODc1ODA3ZDliNTE2NzA4ZDc0ODM1ZGU4NzgyMjY4NmI4MjU1ZGE5YTU3YzcwMGNjNWQ5IiwiaWF0IjoxNjgwNjU5MzgwLCJleHAiOjE2ODEwOTEzODB9.muTp6CZFMebMM2KXLtGZl5eogLh2b6tNHbwl_77lQhs"
}

### 
POST http://localhost:5000/register
Content-Type: application/json

{
    "username" : "usernamedemo3",
    "password": "passworddemo3"
}