GET http://localhost:5500/reqUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgxODA0MzczLCJleHAiOjE2ODE4MDQ5NzN9.MAsp4R4VoUDRS0zH6FH5wgaLX5Be0pDdKT3oLV5JEm4

###

POST http://localhost:5500/login
Content-Type: application/json

{
   "username":"usernamedemo1",
   "password":"passworddemo1"
}
###
POST http://localhost:5500/changeUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgxODA0MzczLCJleHAiOjE2ODE4MDQ5NzN9.MAsp4R4VoUDRS0zH6FH5wgaLX5Be0pDdKT3oLV5JEm4
Content-Type: application/json

{
   "listCart":[]
}

###
POST http://localhost:5500/refresh
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6Ijk5M2E2ZjA3NjMzYmE1ODc0MGY2ZTljODYxZDViNWZiNDUwMDAzODQ4NGMzMTE0YzQyN2JlNjNiNWE4NzUyNDQwNzBlOWRjOGY3YWFlM2FjYTJjNzlmNzU0NzcwMGFkNjRhZjBkODVmZGE3ZDc0ODk4NGRjZWYzODNjMTM3ZjRiIiwiaWF0IjoxNjgxNzg4MzM3LCJleHAiOjE2ODIyMjAzMzd9.xwCasvYQZI-OOrKpZ-8XGefug6I_pfTkpCpOTaS5e3o"
}