GET http://localhost:5500/reqUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRmYXN0MTEiLCJwYXNzd29yZCI6ImRmYXN0MTciLCJpYXQiOjE2ODAwOTg2NjksImV4cCI6MTY4MDA5ODY5OX0.fEHFdyAHdCsilYWAsH23vzjVUTrbjhzPeAGQLIzEoAg
###
POST http://localhost:5500/login
Content-Type: application/json

{
    "username" : "usernamedemo1",
    "password": "passworddemo1"
}
