GET http://localhost:5500/reqUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgxMzg0ODQ5LCJleHAiOjE2ODEzODQ4Nzl9.LcBr7LYq7LXdTIa1fIw_fr_g9ZfyI0z7Uwn9N24fpSI

###

POST http://localhost:5500/login
Content-Type: application/json

{
   "email":"dfast17@gmail.com"
}
###
POST http://localhost:5500/changeUser
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjgxNzg4MzM3LCJleHAiOjE2ODE3ODgzNjd9.PBKe0Rd1qudjWrToXim_prLn2Fc_CnYwCnJziMacfIU
Content-Type: application/json

{
   "listCart":[{
  "id": "1",
  "url": "https://asset.msi.com/resize/image/global/product/product_162175108621129650150f18f256a57cdb5001e680.png62405b38c58fe0f07fcef2367d8a9ba1/400.png",
  "title": "Msi Bravo",
  "brand": "Msi",
  "type": "laptop",
  "price": 800,
  "quantity": 1,
  "total": 800,
  "detail": [
   {
    "cpu": {
     "type": "AMD Ryzen 7 5000 Series",
     "implementation": "5800H"
    },
    "audio": {
     "has_microphone": true,
     "has_headphone_jack": true
    },
    "video": {
     "manufacturer": "NVIDIA",
     "internal_video_card_type": "Dedicated",
     "separate_video_card_type": "AMD Radeon RX 6600"
    },
    "camera": {
     "has_camera_front": true,
     "camera_front_resolution__p": 720
    },
    "design": {
     "color": "Black",
     "material": "Plastic",
     "color_name": "Black"
    },
    "memory": {
     "type": "DDR4",
     "ram__gb": 16,
     "max_ram__gb": 64
    },
    "battery": {
     "technology": "Lithium-ion polymer",
     "battery_cells": "4-cell"
    },
    "display": {
     "size__inch": 15.6,
     "refresh_rate__hz": 144,
     "resolution__pixels": "1920x1080"
    },
    "general": {
     "mpn": "Bravo15020",
     "year": 2023,
     "brand": "MSI"
    },
    "network": {
     "type_wlan_controller": "Wireless-AX"
    },
    "storage": {
     "type": "SSD",
     "capacity__gb": 512,
     "ssd_capacity__gb": 512
    },
    "keyboard": {
     "has_light": true
    },
    "security": {},
    "software": {
     "os": "Windows 11 Home"
    },
    "measurements": {
     "weight__g": 2100.13
    },
    "ports_interfaces": {
     "number_of_hdmi": 1
    }
   }
  ]
 }]
}